/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Old;

import Interface.Menu;
import _Old.Fase1;
import java.awt.event.ActionListener;

/**
 *
 * @author Clayton
 */
public class QuadroDecisao extends javax.swing.JPanel {
    
    /**
     * Creates new form QuadroDecisao1
     * @param texto
     * @param decisao1
     * @param decisao2
     */
    private int numQuadro;

    
    public QuadroDecisao(int numQuadro, String texto, String decisao1, String decisao2) {
        initComponents();
        atualizarStatus();
        nomeJogador.setText(Menu.jogador.getNome());
        this.numQuadro = numQuadro;
        areaTexto.setText(texto);
        botaoOpcao1.setText(decisao1);
        botaoOpcao2.setText(decisao2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        botaoOpcao1 = new javax.swing.JButton();
        botaoOpcao2 = new javax.swing.JButton();
        areaTexto = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        barraEmocional = new javax.swing.JProgressBar();
        barraSanidade = new javax.swing.JProgressBar();
        barraCarisma = new javax.swing.JProgressBar();
        barraCoragem = new javax.swing.JProgressBar();
        nomeJogador = new javax.swing.JLabel();
        labelSanidade = new javax.swing.JLabel();
        labelEmocional = new javax.swing.JLabel();
        labelCarisma = new javax.swing.JLabel();
        labelCoragem = new javax.swing.JLabel();
        percSanidade = new javax.swing.JLabel();
        percEmocional = new javax.swing.JLabel();
        percCarisma = new javax.swing.JLabel();
        percCoragem = new javax.swing.JLabel();

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoOpcao1.setText("Opcao1");
        botaoOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcao1ActionPerformed(evt);
            }
        });

        botaoOpcao2.setText("Opcao2");
        botaoOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcao2ActionPerformed(evt);
            }
        });

        areaTexto.setEditable(false);
        areaTexto.setText("areaTexto");
        areaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        areaTexto.setRequestFocusEnabled(false);

        barraEmocional.setForeground(new java.awt.Color(153, 255, 204));
        barraEmocional.setMaximum(10);

        barraSanidade.setForeground(new java.awt.Color(255, 51, 51));
        barraSanidade.setMaximum(10);

        barraCarisma.setForeground(new java.awt.Color(102, 255, 102));
        barraCarisma.setMaximum(10);

        barraCoragem.setForeground(new java.awt.Color(51, 102, 255));
        barraCoragem.setMaximum(10);

        nomeJogador.setText("nomeJogador");

        labelSanidade.setText("Sanidade");

        labelEmocional.setText("Emocional");

        labelCarisma.setText("Carisma");

        labelCoragem.setText("Coragem");

        percSanidade.setText("%");

        percEmocional.setText("%");

        percCarisma.setText("%");

        percCoragem.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraSanidade, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(nomeJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraEmocional, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(barraCarisma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(barraCoragem, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCoragem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percCoragem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSanidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percSanidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEmocional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percEmocional))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCarisma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percCarisma)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(botaoOpcao1)
                                .addGap(84, 84, 84)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(botaoOpcao2))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(areaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoOpcao1)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoOpcao2)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSeparator3))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSanidade)
                    .addComponent(percSanidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraSanidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmocional)
                    .addComponent(percEmocional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraEmocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarisma)
                    .addComponent(percCarisma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoragem)
                    .addComponent(percCoragem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCoragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcao1ActionPerformed
     
        
        switch(numQuadro){
            case 1:
                Menu.jogador.reduzirEmocional();
                Menu.jogador.reduzirCoragem();           
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
        }
        atualizarStatus();
        Fase1.levelClear();
    }//GEN-LAST:event_botaoOpcao1ActionPerformed

    private void botaoOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcao2ActionPerformed
        switch(numQuadro){
            case 1:
                Menu.jogador.aumentarCoragem();
                Menu.jogador.reduzirSanidade();
                Menu.jogador.reduzirEmocional();
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
        } 
        atualizarStatus();
        Fase1.levelClear();
    }//GEN-LAST:event_botaoOpcao2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField areaTexto;
    private javax.swing.JProgressBar barraCarisma;
    private javax.swing.JProgressBar barraCoragem;
    private javax.swing.JProgressBar barraEmocional;
    private javax.swing.JProgressBar barraSanidade;
    private javax.swing.JButton botaoOpcao1;
    private javax.swing.JButton botaoOpcao2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCarisma;
    private javax.swing.JLabel labelCoragem;
    private javax.swing.JLabel labelEmocional;
    private javax.swing.JLabel labelSanidade;
    private javax.swing.JLabel nomeJogador;
    private javax.swing.JLabel percCarisma;
    private javax.swing.JLabel percCoragem;
    private javax.swing.JLabel percEmocional;
    private javax.swing.JLabel percSanidade;
    // End of variables declaration//GEN-END:variables


    private void atualizarStatus(){       
        barraSanidade.setValue(Menu.jogador.getSanidade());
        percSanidade.setText(String.format("%d%%",(barraSanidade.getValue()*10)));
        barraEmocional.setValue(Menu.jogador.getEmocional());
        percEmocional.setText(String.format("%d%%",(barraEmocional.getValue()*10)));
        barraCarisma.setValue(Menu.jogador.getCarisma());
        percCarisma.setText(String.format("%d%%",(barraCarisma.getValue()*10)));
        barraCoragem.setValue(Menu.jogador.getCoragem());
        percCoragem.setText(String.format("%d%%",(barraCoragem.getValue()*10)));
    }
}
