/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import BancoDados.OperacoesBD;
import Elementos.Jogador;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class TelaLogin extends javax.swing.JFrame {
    public Jogador jogador;
    private JPanel j1;
    private int tipoTela;
    private KeyListener loginKL;
    private KeyListener registroKL;
    
    
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
        tipoTela=0; // 0 = login, 1 = registro
        
        loginKL = new KeyAdapter() {
        public void keyReleased(KeyEvent e) {
            checkLoginEmpty();
        }};
        
        registroKL = new KeyAdapter() {
        public void keyReleased(KeyEvent e) {
            checkRegistroEmpty();
        }};
        
        AddKeyListenersOnEvent();
        jogador = new Jogador("abinhogameplay","amigodamariana","Abinho Gameplay");
        if(!OperacoesBD.checkIfUserExists(jogador.getUsuario())) 
        try {
            OperacoesBD.InserirJogador(jogador);
        } catch (SQLIntegrityConstraintViolationException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        Menu m = new Menu(jogador);
        m.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        labelUsuarioLogin = new javax.swing.JLabel();
        labelSenhaLogin = new javax.swing.JLabel();
        tbUsuarioLogin = new javax.swing.JTextField();
        botaoLogar = new javax.swing.JButton();
        botaoRegistrarLogin = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        tbSenhaLogin = new javax.swing.JPasswordField();
        registro = new javax.swing.JPanel();
        labelUsuarioRegistro = new javax.swing.JLabel();
        labelSenhaRegistro = new javax.swing.JLabel();
        tbUsuarioRegistro = new javax.swing.JTextField();
        botaoRegistrarRegistro = new javax.swing.JButton();
        labelApelidoRegistro = new javax.swing.JLabel();
        tbApelidoRegistro = new javax.swing.JTextField();
        labelRegistro = new javax.swing.JLabel();
        tbSenhaRegistro = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        tela.setLayout(new java.awt.CardLayout());

        labelUsuarioLogin.setText("Usuário");

        labelSenhaLogin.setText("Senha");

        botaoLogar.setText("Login");
        botaoLogar.setEnabled(false);
        botaoLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogarActionPerformed(evt);
            }
        });

        botaoRegistrarLogin.setText("Registrar");
        botaoRegistrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarLoginActionPerformed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(80, 200, 40));
        labelLogin.setText("Login");

        tbSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSenhaLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelLogin))
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginLayout.createSequentialGroup()
                            .addComponent(botaoRegistrarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botaoLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginLayout.createSequentialGroup()
                            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                                    .addComponent(labelUsuarioLogin)
                                    .addGap(10, 10, 10))
                                .addGroup(loginLayout.createSequentialGroup()
                                    .addComponent(labelSenhaLogin)
                                    .addGap(16, 16, 16)))
                            .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tbSenhaLogin)
                                .addComponent(tbUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogin)
                .addGap(29, 29, 29)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelUsuarioLogin))
                    .addComponent(tbUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaLogin)
                    .addComponent(tbSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRegistrarLogin)
                    .addComponent(botaoLogar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tela.add(login, "card2");

        registro.setPreferredSize(new java.awt.Dimension(286, 202));

        labelUsuarioRegistro.setText("Usuário");

        labelSenhaRegistro.setText("Senha");

        botaoRegistrarRegistro.setText("Registrar");
        botaoRegistrarRegistro.setEnabled(false);
        botaoRegistrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarRegistroActionPerformed(evt);
            }
        });

        labelApelidoRegistro.setText("Apelido");

        labelRegistro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelRegistro.setForeground(new java.awt.Color(20, 20, 240));
        labelRegistro.setText("Registro");
        labelRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro);
        registro.setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(labelApelidoRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbApelidoRegistro))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUsuarioRegistro)
                                    .addComponent(labelSenhaRegistro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbUsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(tbSenhaRegistro)))))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(botaoRegistrarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(labelRegistro)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addComponent(labelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuarioRegistro)
                    .addComponent(tbUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaRegistro)
                    .addComponent(tbSenhaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbApelidoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApelidoRegistro))
                .addGap(18, 18, 18)
                .addComponent(botaoRegistrarRegistro)
                .addContainerGap())
        );

        tela.add(registro, "telaRegistro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRegistrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarRegistroActionPerformed
        if(!String.valueOf(tbUsuarioRegistro.getText()).isEmpty() && 
           !String.valueOf(tbSenhaRegistro.getPassword()).isEmpty() && 
           !String.valueOf(tbApelidoRegistro.getText()).isEmpty())
        {
            if(OperacoesBD.checkIfUserExists(String.valueOf(tbUsuarioRegistro.getText())))
                JOptionPane.showMessageDialog(null, "Esse usuário já existe, tente outro nome.", "Erro ao cadastrar", JOptionPane.WARNING_MESSAGE);
            else{
                try{
                    OperacoesBD.InserirJogador(new Jogador(tbUsuarioRegistro.getText(), String.valueOf(tbSenhaRegistro.getPassword()), tbApelidoRegistro.getText()));              
                    trocarTela();
                } catch(SQLIntegrityConstraintViolationException e){
                    JOptionPane.showMessageDialog(null, "Esse usuário já existe, tente outro nome.\n\n" + e, "Erro ao cadastrar", JOptionPane.WARNING_MESSAGE);
                }     
            }
        }
        else JOptionPane.showMessageDialog(null, "Existem campos em branco, então não é possível realizar o cadastro.","Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_botaoRegistrarRegistroActionPerformed

    private void botaoRegistrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarLoginActionPerformed
        trocarTela();
    }//GEN-LAST:event_botaoRegistrarLoginActionPerformed

    private void botaoLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogarActionPerformed
        if(!isLoginEmpty())
        {
            if(!OperacoesBD.verifyLogin(String.valueOf(tbUsuarioLogin.getText()),String.valueOf(tbSenhaLogin.getPassword()))){
                System.out.println("Erro ao logar, usuario ou senha incorretos.");
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos, tente novamente.", "Erro ao logar", JOptionPane.WARNING_MESSAGE);
            }    
            else
                System.out.println("Login realizado com sucesso.");
                //
        }
        else JOptionPane.showMessageDialog(null, "Existem campos em branco, então não é possível realizar o cadastro.","Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_botaoLogarActionPerformed

    private void tbSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSenhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSenhaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    
    private void trocarTela(){
        tela.removeAll(); // Famoso cascade
        if(tipoTela==0){
            tbUsuarioRegistro.setText(tbUsuarioLogin.getText());
            tbUsuarioLogin.setText("");
            tbSenhaRegistro.setText(String.valueOf(tbSenhaLogin.getPassword()));
            tbSenhaLogin.setText("");
            //botaoRegistrarRegistro.setEnabled(false);
            isRegistroEmpty();
            tela.add(registro);
        }
        else{
            tbUsuarioLogin.setText(tbUsuarioRegistro.getText());
            tbUsuarioRegistro.setText("");
            tbSenhaRegistro.setText("");
            tbApelidoRegistro.setText("");
            //botaoLogar.setEnabled(false);
            isLoginEmpty();
            tela.add(login);
        }
        tipoTela=1-tipoTela;

        tela.repaint();
        tela.revalidate();   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogar;
    private javax.swing.JButton botaoRegistrarLogin;
    private javax.swing.JButton botaoRegistrarRegistro;
    private javax.swing.JLabel labelApelidoRegistro;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JLabel labelSenhaLogin;
    private javax.swing.JLabel labelSenhaRegistro;
    private javax.swing.JLabel labelUsuarioLogin;
    private javax.swing.JLabel labelUsuarioRegistro;
    private javax.swing.JPanel login;
    private javax.swing.JPanel registro;
    private javax.swing.JTextField tbApelidoRegistro;
    private javax.swing.JPasswordField tbSenhaLogin;
    private javax.swing.JPasswordField tbSenhaRegistro;
    private javax.swing.JTextField tbUsuarioLogin;
    private javax.swing.JTextField tbUsuarioRegistro;
    private javax.swing.JPanel tela;
    // End of variables declaration//GEN-END:variables

    private void AddKeyListenersOnEvent() {   
        tbUsuarioLogin.addKeyListener(loginKL);
        tbSenhaLogin.addKeyListener(loginKL);
        tbUsuarioRegistro.addKeyListener(registroKL);
        tbSenhaRegistro.addKeyListener(registroKL);
        tbApelidoRegistro.addKeyListener(registroKL);          
    }
    
    private boolean isLoginEmpty(){
        if(String.valueOf(tbUsuarioLogin.getText()).isEmpty() ||
           String.valueOf(tbSenhaLogin.getPassword()).isEmpty())
            return true;
        else
            return false;
    }
    
    private boolean isRegistroEmpty(){
        if(String.valueOf(tbUsuarioRegistro.getText()).isEmpty() ||
           String.valueOf(tbSenhaRegistro.getPassword()).isEmpty() || 
           String.valueOf(tbApelidoRegistro.getText()).isEmpty())
                return true;
            else
                return false;
    }
    
    private void checkLoginEmpty(){
        if(!String.valueOf(tbUsuarioLogin.getText()).isEmpty() && 
           !String.valueOf(tbSenhaLogin.getPassword()).isEmpty())
            botaoLogar.setEnabled(true);
        else
            botaoLogar.setEnabled(false);
    }
    
    private void checkRegistroEmpty(){
        if(!String.valueOf(tbUsuarioRegistro.getText()).isEmpty() && 
           !String.valueOf(tbSenhaRegistro.getPassword()).isEmpty() && 
           !String.valueOf(tbApelidoRegistro.getText()).isEmpty())
                botaoRegistrarRegistro.setEnabled(true);
            else
                botaoRegistrarRegistro.setEnabled(false);
    }
}
