/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BancoDados.OperacoesBD;
import Elementos.*;
import Principal.JogoHospicio;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Jogador jogador;
    private Personagem personagem;
    private Etapa etapaAtual;
    private Save saveAtual;
    
    private int numEtapaAtual;
    private int numSlotSaveAtual;
    private int tipoQuadroAtual;
    
    /**
     * Creates new form QuadroTemporario
     */
    public TelaPrincipal(){
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }
    
    public TelaPrincipal(Jogador j, Personagem p, Save sA, int nSSA) {
        this();
        this.jogador = j;
        this.personagem  = p;
        this.saveAtual = sA;
        this.numSlotSaveAtual = nSSA;
        this.numEtapaAtual = (saveAtual.getEtapa_atual() == 0)? 1 : saveAtual.getEtapa_atual();
        this.etapaAtual = OperacoesBD.getEtapa(numEtapaAtual); 
        nomeJogador.setText(jogador.getApelido());
        this.tipoQuadroAtual = etapaAtual.getTipo_quadro();
        atualizarInterface();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JPanel();
        status = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        barraEmocional = new javax.swing.JProgressBar();
        barraSanidade = new javax.swing.JProgressBar();
        barraCarisma = new javax.swing.JProgressBar();
        barraCoragem = new javax.swing.JProgressBar();
        nomeJogador = new javax.swing.JLabel();
        labelSanidade = new javax.swing.JLabel();
        labelEmocional = new javax.swing.JLabel();
        labelCarisma = new javax.swing.JLabel();
        labelCoragem = new javax.swing.JLabel();
        percSanidade = new javax.swing.JLabel();
        percEmocional = new javax.swing.JLabel();
        percCarisma = new javax.swing.JLabel();
        percCoragem = new javax.swing.JLabel();
        alternar = new javax.swing.JPanel();
        decisao = new javax.swing.JPanel();
        botaoOpcao1 = new javax.swing.JButton();
        botaoOpcao2 = new javax.swing.JButton();
        areaTextoDecisao = new javax.swing.JFormattedTextField();
        avancar = new javax.swing.JPanel();
        botaoAvancar = new javax.swing.JButton();
        areaTextoAvancar = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        barraEmocional.setForeground(new java.awt.Color(153, 255, 204));
        barraEmocional.setMaximum(20);

        barraSanidade.setForeground(new java.awt.Color(255, 51, 51));
        barraSanidade.setMaximum(20);

        barraCarisma.setForeground(new java.awt.Color(102, 255, 102));
        barraCarisma.setMaximum(20);

        barraCoragem.setForeground(new java.awt.Color(51, 102, 255));
        barraCoragem.setMaximum(20);

        nomeJogador.setText("nomeJogador");

        labelSanidade.setText("Sanidade");

        labelEmocional.setText("Emocional");

        labelCarisma.setText("Carisma");

        labelCoragem.setText("Coragem");

        percSanidade.setText("%");

        percEmocional.setText("%");

        percCarisma.setText("%");

        percCoragem.setText("%");

        javax.swing.GroupLayout statusLayout = new javax.swing.GroupLayout(status);
        status.setLayout(statusLayout);
        statusLayout.setHorizontalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraSanidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nomeJogador, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(barraEmocional, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(barraCarisma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(barraCoragem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(statusLayout.createSequentialGroup()
                        .addComponent(labelCoragem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percCoragem))
                    .addGroup(statusLayout.createSequentialGroup()
                        .addComponent(labelSanidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percSanidade))
                    .addGroup(statusLayout.createSequentialGroup()
                        .addComponent(labelEmocional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percEmocional))
                    .addGroup(statusLayout.createSequentialGroup()
                        .addComponent(labelCarisma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(percCarisma)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        statusLayout.setVerticalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSeparator3))
            .addGroup(statusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSanidade)
                    .addComponent(percSanidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraSanidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmocional)
                    .addComponent(percEmocional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraEmocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarisma)
                    .addComponent(percCarisma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoragem)
                    .addComponent(percCoragem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCoragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        alternar.setLayout(new java.awt.CardLayout());

        botaoOpcao1.setText("Opcao1");
        botaoOpcao1.setMaximumSize(new java.awt.Dimension(75, 25));
        botaoOpcao1.setMinimumSize(new java.awt.Dimension(75, 25));
        botaoOpcao1.setPreferredSize(new java.awt.Dimension(75, 25));
        botaoOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcao1ActionPerformed(evt);
            }
        });

        botaoOpcao2.setText("Opcao2");
        botaoOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcao2ActionPerformed(evt);
            }
        });

        areaTextoDecisao.setEditable(false);
        areaTextoDecisao.setText("areaTexto");
        areaTextoDecisao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        areaTextoDecisao.setRequestFocusEnabled(false);

        javax.swing.GroupLayout decisaoLayout = new javax.swing.GroupLayout(decisao);
        decisao.setLayout(decisaoLayout);
        decisaoLayout.setHorizontalGroup(
            decisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decisaoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(decisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, decisaoLayout.createSequentialGroup()
                        .addComponent(botaoOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoOpcao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(areaTextoDecisao, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        decisaoLayout.setVerticalGroup(
            decisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decisaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(areaTextoDecisao, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(decisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        alternar.add(decisao, "card2");

        botaoAvancar.setText("Avançar");
        botaoAvancar.setMaximumSize(new java.awt.Dimension(75, 25));
        botaoAvancar.setMinimumSize(new java.awt.Dimension(75, 25));
        botaoAvancar.setPreferredSize(new java.awt.Dimension(75, 25));
        botaoAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAvancarActionPerformed(evt);
            }
        });

        areaTextoAvancar.setEditable(false);
        areaTextoAvancar.setText("areaTexto");
        areaTextoAvancar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        areaTextoAvancar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout avancarLayout = new javax.swing.GroupLayout(avancar);
        avancar.setLayout(avancarLayout);
        avancarLayout.setHorizontalGroup(
            avancarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avancarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(avancarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avancarLayout.createSequentialGroup()
                        .addComponent(areaTextoAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avancarLayout.createSequentialGroup()
                        .addComponent(botaoAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        avancarLayout.setVerticalGroup(
            avancarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avancarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(areaTextoAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        alternar.add(avancar, "card3");

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(alternar, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alternar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcao2ActionPerformed
        avancarEtapa(2);
    }//GEN-LAST:event_botaoOpcao2ActionPerformed

    private void botaoOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcao1ActionPerformed
        avancarEtapa(1);
    }//GEN-LAST:event_botaoOpcao1ActionPerformed

    private void botaoAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAvancarActionPerformed
        avancarEtapa(0);
    }//GEN-LAST:event_botaoAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alternar;
    private javax.swing.JFormattedTextField areaTextoAvancar;
    private javax.swing.JFormattedTextField areaTextoDecisao;
    private javax.swing.JPanel avancar;
    private javax.swing.JProgressBar barraCarisma;
    private javax.swing.JProgressBar barraCoragem;
    private javax.swing.JProgressBar barraEmocional;
    private javax.swing.JProgressBar barraSanidade;
    private javax.swing.JButton botaoAvancar;
    private javax.swing.JButton botaoOpcao1;
    private javax.swing.JButton botaoOpcao2;
    private javax.swing.JPanel decisao;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCarisma;
    private javax.swing.JLabel labelCoragem;
    private javax.swing.JLabel labelEmocional;
    private javax.swing.JLabel labelSanidade;
    private javax.swing.JLabel nomeJogador;
    private javax.swing.JLabel percCarisma;
    private javax.swing.JLabel percCoragem;
    private javax.swing.JLabel percEmocional;
    private javax.swing.JLabel percSanidade;
    private javax.swing.JPanel status;
    private javax.swing.JPanel tela;
    // End of variables declaration//GEN-END:variables

    private void avancarEtapa(int botao){
        if(etapaAtual.getRef_op1() > 0){
            Etapa proxEtapa;
            
            atualizarStatus();
            if(botao < 2){
                proxEtapa = OperacoesBD.getEtapa(etapaAtual.getRef_op1());
            }
            else{
                proxEtapa = OperacoesBD.getEtapa(etapaAtual.getRef_op2());
            }
            if(tipoQuadroAtual != proxEtapa.getTipo_quadro()){
                tipoQuadroAtual = proxEtapa.getTipo_quadro();
            }
            etapaAtual = proxEtapa;
            atualizarInterface();
              
        }
        else{
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou o jogo!", "WOW", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void atualizarInterface(){
        alternar.removeAll();
        
        if(etapaAtual.getTipo_quadro() == 0){
            alternar.add(decisao);
            botaoOpcao1.setText(etapaAtual.getTextobt1());
            botaoOpcao2.setText(etapaAtual.getTextobt2());
            areaTextoDecisao.setText(String.format(etapaAtual.getDescricao()));
        }
        else{
            alternar.add(avancar);
            botaoOpcao1.setText("");
            botaoOpcao2.setText("");
            areaTextoAvancar.setText(String.format(etapaAtual.getDescricao()));
        }
        
        barraSanidade.setValue(personagem.getSanidade());
        percSanidade.setText(String.format("%d%%",(barraSanidade.getValue()*5)));
        barraEmocional.setValue(personagem.getEmocional());
        percEmocional.setText(String.format("%d%%",(barraEmocional.getValue()*5)));
        barraCarisma.setValue(personagem.getCarisma());
        percCarisma.setText(String.format("%d%%",(barraCarisma.getValue()*5)));
        barraCoragem.setValue(personagem.getCoragem());
        percCoragem.setText(String.format("%d%%",(barraCoragem.getValue()*5)));

        tela.repaint();
        tela.revalidate(); 
    }
    
    private void atualizarStatus(){
        if(tipoQuadroAtual == 0){
            personagem.alterarSanidade(etapaAtual.getImp_sanidade1());
            personagem.alterarEmocional(etapaAtual.getImp_emocional1());
            personagem.alterarCarisma(etapaAtual.getImp_carisma1());
            personagem.alterarCoragem(etapaAtual.getImp_coragem1());
        }
        else{
            personagem.alterarSanidade(etapaAtual.getImp_sanidade2());
            personagem.alterarEmocional(etapaAtual.getImp_emocional2());
            personagem.alterarCarisma(etapaAtual.getImp_carisma2());
            personagem.alterarCoragem(etapaAtual.getImp_coragem2());
        }
        
    }
}
